// Boş sunu: yer tutucuya yaz, yeni slayt ekle, kaydet
import { createRequire } from 'module'
import fs from 'fs'
const require = createRequire('/opt/npm-tools/node_modules/')
const { chromium } = require('playwright')
const OUT = process.argv[2]; fs.mkdirSync(OUT, { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const page = await ctx.newPage()
const external = []
page.on('request', r => { const u = r.url(); if (!/^(http:\/\/localhost|data:|blob:)/.test(u)) external.push(u) })
page.on('pageerror', e => console.log('[pageerror]', e.message))
await page.goto('http://localhost:8703/modules/vista/index.html')
await page.waitForFunction(() => window.__ewrekaVista && window.__ewrekaVista.slidesStore.slides.length >= 1)
await page.waitForTimeout(1000)
console.log('başlık:', await page.title())
const title = page.locator('.canvas .editable-element-text').first()
await title.click(); await page.waitForTimeout(200)
await title.locator('.ProseMirror').click()
await page.keyboard.type('Çeyrek Sonuçları 2026')
const sub = page.locator('.canvas .editable-element-text').nth(1)
await sub.click(); await page.waitForTimeout(200)
await sub.locator('.ProseMirror').click()
await page.keyboard.type('Ewreka Digital — İstanbul')
await page.mouse.click(700, 830); await page.waitForTimeout(500)
await page.screenshot({ path: `${OUT}/n1-baslik.png` })
await page.click('.thumbnails .btn:has-text("Yeni slayt")'); await page.waitForTimeout(800)
await page.screenshot({ path: `${OUT}/n2-yeni-slayt.png` })
console.log('slayt sayısı:', await page.evaluate(() => window.__ewrekaVista.slidesStore.slides.length), 'başlık:', await page.title())
// Geri al / yinele
console.log('durum:', await page.evaluate(() => { const v = window.__ewrekaVista; return { cur: v.snapshotStore.snapshotCursor, len: v.snapshotStore.snapshotLength, dis: v.mainStore.disableHotkeys, active: document.activeElement && document.activeElement.className } }))
await page.keyboard.press('Control+z'); await page.waitForTimeout(600)
console.log('geri al sonrası slayt:', await page.evaluate(() => window.__ewrekaVista.slidesStore.slides.length))
await page.keyboard.press('Control+y'); await page.waitForTimeout(600)
console.log('yinele sonrası slayt:', await page.evaluate(() => window.__ewrekaVista.slidesStore.slides.length))
const [dl] = await Promise.all([page.waitForEvent('download'), page.keyboard.press('Control+s')])
await dl.saveAs(`${OUT}/yeni.pptx`)
console.log('indirildi', dl.suggestedFilename(), 'başlık:', await page.title())
console.log('DIŞ İSTEKLER:', external.length ? external : 'yok')
await browser.close()
