import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('/opt/npm-tools/node_modules/playwright');
const OUT = process.argv[2];
const b = await chromium.launch(); const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:8702/modules/nota/index.html?file=/test-files/ornek.docx');
await page.waitForFunction(() => document.body.classList.contains('nota-ready') && window.__nota.sd?.activeEditor, null, { timeout: 30000 });
await page.waitForTimeout(1000);
const h = await page.evaluate(() => { const r = document.querySelector('.superdoc-page-header').getBoundingClientRect(); return { x: r.x + 60, y: r.y + r.height / 2 }; });
await page.mouse.dblclick(h.x, h.y);
await page.waitForTimeout(800);
await page.keyboard.press('End'); await page.keyboard.type(' (düzenlendi)');
await page.waitForTimeout(400);
console.log(await page.evaluate(() => [...document.querySelectorAll('.presentation-editor__mode-banner, [class*="banner"]')].map((e) => e.innerText).filter(Boolean)));
await page.screenshot({ path: OUT + '/09-ustbilgi-duzenleme.png' });
await page.keyboard.press('Escape'); await page.waitForTimeout(400);
const dl = page.waitForEvent('download'); await page.keyboard.press('Control+s'); const d = await dl; await d.saveAs(OUT + '/ustbilgi.docx');
await b.close();
