// Ewreka Vista: yalnızca Windows/macOS sistem yazı tipleri (uzaktan/paketlenmiş web fontu yok)
export const FONTS = [
  { label: 'Varsayılan', value: '' },
  { label: 'Calibri', value: 'Calibri' },
  { label: 'Calibri Light', value: 'Calibri Light' },
  { label: 'Arial', value: 'Arial' },
  { label: 'Arial Black', value: 'Arial Black' },
  { label: 'Segoe UI', value: 'Segoe UI' },
  { label: 'Helvetica Neue', value: 'Helvetica Neue' },
  { label: 'Helvetica', value: 'Helvetica' },
  { label: 'Verdana', value: 'Verdana' },
  { label: 'Tahoma', value: 'Tahoma' },
  { label: 'Trebuchet MS', value: 'Trebuchet MS' },
  { label: 'Century Gothic', value: 'Century Gothic' },
  { label: 'Franklin Gothic Medium', value: 'Franklin Gothic Medium' },
  { label: 'Gill Sans', value: 'Gill Sans' },
  { label: 'Times New Roman', value: 'Times New Roman' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Cambria', value: 'Cambria' },
  { label: 'Garamond', value: 'Garamond' },
  { label: 'Palatino Linotype', value: 'Palatino Linotype' },
  { label: 'Book Antiqua', value: 'Book Antiqua' },
  { label: 'Courier New', value: 'Courier New' },
  { label: 'Consolas', value: 'Consolas' },
  { label: 'Lucida Console', value: 'Lucida Console' },
  { label: 'Menlo', value: 'Menlo' },
  { label: 'Impact', value: 'Impact' },
  { label: 'Comic Sans MS', value: 'Comic Sans MS' },
]
